# Generated by Django 6.0 on 2026-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='প্ল্যানের নাম (যেমন: Pro Monthly)', max_length=100)),
                ('plan_type', models.CharField(choices=[('Free', 'Free Core'), ('ExamPack', 'Exam Pack (One-time)'), ('Monthly', 'Pro Monthly'), ('Yearly', 'Pro Yearly')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ai_credits_limit', models.IntegerField(default=50, help_text='প্রতি মাসে কয়টি AI প্রশ্ন জেনারেট করতে পারবে (-1 মানে আনলিমিটেড)')),
                ('ielts_mock_limit', models.IntegerField(default=0, help_text='কয়টি ফুল IELTS মডেল টেস্ট দিতে পারবে (-1 মানে আনলিমিটেড)')),
                ('features', models.TextField(blank=True, help_text='ফিচারগুলো কমা (,) দিয়ে লিখুন')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
    ]
