# Generated by Django 5.0.6 on 2026-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='bkash_number',
            field=models.CharField(default='018********', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='nagad_number',
            field=models.CharField(default='018********', max_length=15),
        ),
    ]
