# Generated by Django 6.0 on 2026-02-22 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(choices=[('Free', 'Free'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Free', max_length=20)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_question_count', models.IntegerField(default=0)),
                ('hourly_question_count', models.IntegerField(default=0)),
                ('hourly_written_count', models.IntegerField(default=0)),
                ('extra_tests_balance', models.IntegerField(default=0)),
                ('last_hour_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_month_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
