# Generated by Django 6.0 on 2026-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ielts_mock_count',
            field=models.IntegerField(default=0),
        ),
    ]
