# Generated by Django 6.0 on 2026-03-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ielts_mock_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hourly_question_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_written_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_hour_reset',
        ),
    ]
