# Generated by Django 5.0.6 on 2026-03-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
