# Generated by Django 5.0.6 on 2026-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pendingregistration_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
