# Generated by Django 6.0 on 2026-03-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_exam_ai_analysis_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='level',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
