# Generated by Django 6.0.2 on 2026-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questionbank_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='level',
            field=models.CharField(blank=True, default='Medium', max_length=50),
        ),
    ]
