# Generated by Django 5.0.6 on 2026-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_exam_share_image_url_alter_exam_id_alter_question_id_and_more'),
        ('weak_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exam_questions', to='weak_topics.topictag'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='question_bank_questions', to='weak_topics.topictag'),
        ),
    ]
