# Generated by Django 5.0.6 on 2026-04-05 14:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_tags_questionbank_tags'),
        ('weak_topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, default='Medium', max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('question_type', models.CharField(max_length=50)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('explanation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='ai_generated_questions', to='weak_topics.topictag')),
            ],
        ),
    ]
