# Generated by Django 6.0 on 2026-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Direct link to the featured image (YouTube/External).', max_length=500, null=True),
        ),
    ]
