# Generated by Django 6.0 on 2026-02-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_passage_question_test_choice_answer_questionsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinguseranswer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='test',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='readinguseranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='readingresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='readingresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readinguseranswer',
            name='test',
        ),
        migrations.RemoveField(
            model_name='readinguseranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadingChoice',
        ),
        migrations.DeleteModel(
            name='ReadingPassage',
        ),
        migrations.DeleteModel(
            name='ReadingQuestion',
        ),
        migrations.DeleteModel(
            name='ReadingResult',
        ),
        migrations.DeleteModel(
            name='ReadingTest',
        ),
        migrations.DeleteModel(
            name='ReadingUserAnswer',
        ),
    ]
