# Generated by Django 6.0 on 2026-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_remove_readinguseranswer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsection',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('sent_comp', 'Sentence Completion'), ('tfng', 'True/False/Not Given'), ('ynng', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_features', 'Matching Features'), ('matching_info', 'Matching Information'), ('matching_sentence_endings', 'Matching Sentence Endings'), ('summary_completion', 'Summary Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flow_chart_completion', 'Flow Chart Completion'), ('diagram_label_completion', 'Diagram Label Completion'), ('short_answer', 'Short Answer Questions'), ('pick_from_list', 'Pick From List'), ('choose_two', 'Choose TWO')], max_length=32),
        ),
    ]
