# Generated by Django 6.0 on 2026-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_alter_questionsection_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='ielts.choice'),
        ),
    ]
