# Generated by Django 6.0 on 2026-02-24 12:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_remove_useranswer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='questionsection',
            name='instruction_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
