# Generated by Django 6.0 on 2026-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], default='reading', max_length=20),
        ),
    ]
