# Generated by Django 6.0 on 2026-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0008_test_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20),
        ),
    ]
