# Generated by Django 5.0.6 on 2026-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0011_alter_answer_id_alter_choice_id_alter_passage_id_and_more'),
        ('weak_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ielts_questions', to='weak_topics.topictag'),
        ),
    ]
