# Generated by Django 5.0.6 on 2026-04-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0012_question_tags'),
        ('weak_topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='questionsection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ielts_sections', to='weak_topics.topictag'),
        ),
    ]
