# Generated by Django 5.0.6 on 2026-04-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0013_remove_question_tags_questionsection_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsection',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tfng', 'True/False/Not Given (or Yes/No/Not Given)'), ('matching', 'Matching (Headings, Features, Info)'), ('completion', 'Completion / Fill in the Blanks'), ('short_answer', 'Short Answer Questions')], max_length=32),
        ),
    ]
