# Generated by Django 5.0.6 on 2026-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0014_alter_questionsection_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsection',
            name='matching_options',
            field=models.CharField(blank=True, help_text='For Matching: comma-separated list of options (e.g. A,B,C,D or i,ii,iii,iv)', max_length=500),
        ),
    ]
